# Generated by Django 5.2.7 on 2025-11-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='age_group',
            field=models.CharField(blank=True, choices=[('adult', 'Adult'), ('kid', 'Kid')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price_tg',
            field=models.FloatField(default=0.0, verbose_name='Price (KZT)'),
        ),
        migrations.AddField(
            model_name='item',
            name='size_category',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='style',
            field=models.CharField(blank=True, choices=[('minimal', 'Minimal'), ('classic', 'Classic'), ('hi-tech', 'Hi-Tech'), ('modern', 'Modern'), ('loft', 'Loft'), ('ethnic', 'Ethnic')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='item.tag'),
        ),
    ]
